### ISSUE TITLE
Couldn't find the API Key.

### ISSUE THREAD

**Issue by penghongkwek** [Scarjit/PUBGSDK#1]
Could not locate the API Key file.

**Comment by Scarjit** [comment]
Well, obviously i omitted it, so i don't accidentally leak my own key.
Just create a file called "api_key.txt" in the PUBGSDK/TestApp folder and set it to "copy if newer" (in vs) or place it directly into the output folder.
Then open it and paste your api key inside

**Comment by penghongkwek** [comment]
Thank you for the reply. What i meant is what key are you referring to? PUBG game key?

**Comment by Scarjit** [comment]
You can get your API Key on the offical pubg developer site:
https://developer.playbattlegrounds.com/apps?locale=en

**Comment by penghongkwek** [comment]
Ahhhh okay. Thanks mate :) 👍
